"""empty message

Revision ID: 232273676d89
Revises: 90ee183a151e
Create Date: 2024-11-19 20:21:21.967230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "232273676d89"
down_revision = "90ee183a151e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.alter_column("is_hidden", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.alter_column("is_hidden", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
